services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: root
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  
volumes:
  mosquitto-data: